// Copyright (c) 2024-2026 Testsmith.io. All rights reserved.
// Licensed for private, internal, non-commercial use only.
// See LICENSE for full terms.

import * as vm from 'vm';
import * as crypto from 'crypto';
import dayjs from 'dayjs';
import tv4 from 'tv4';
import { JSONPath } from 'jsonpath-plus';
import { DOMParser as XmlDOMParser } from '@xmldom/xmldom';

// ─── querySelector polyfill for xmldom ────────────────────────────────────────
// Handles the limited selector syntax generated by the tree view:
//   "tag", "tag:nth-of-type(n) > child > grandchild", etc.

type XmlNode = { childNodes: ArrayLike<XmlNode>; nodeType: number; tagName?: string; [k: string]: unknown }

// Collect all elements with `tag` that are the nth-of-type among their siblings,
// anywhere in the subtree of `node`.
function xmlFindAll(node: XmlNode, tag: string, nth: number): XmlNode[] {
  const results: XmlNode[] = [];
  const siblings = Array.from(node.childNodes).filter(c => c.nodeType === 1 && c.tagName === tag);
  if (siblings[nth]) results.push(siblings[nth]);
  for (const child of Array.from(node.childNodes)) {
    if (child.nodeType === 1) results.push(...xmlFindAll(child, tag, nth));
  }
  return results;
}

function xmlQuerySelector(root: XmlNode, selector: string): XmlNode | null {
  const parts = selector.trim().split(/\s*>\s*/);

  // First part: search entire subtree
  const m0 = parts[0].match(/^([A-Za-z0-9_:.-]+?)(?::nth-of-type\((\d+)\))?$/);
  if (!m0) return null;
  let candidates = xmlFindAll(root, m0[1], m0[2] ? parseInt(m0[2]) - 1 : 0);

  // Remaining parts: direct-child traversal
  for (let i = 1; i < parts.length; i++) {
    const m = parts[i].match(/^([A-Za-z0-9_:.-]+?)(?::nth-of-type\((\d+)\))?$/);
    if (!m) return null;
    const tag = m[1];
    const idx = m[2] ? parseInt(m[2]) - 1 : 0;
    const next: XmlNode[] = [];
    for (const node of candidates) {
      const children = Array.from(node.childNodes).filter(c => c.nodeType === 1 && c.tagName === tag);
      if (children[idx]) next.push(children[idx]);
    }
    candidates = next;
  }

  return candidates[0] ?? null;
}

function makeSandboxDOMParser() {
  return {
    parseFromString(str: string, mime: string) {
      const doc = new XmlDOMParser().parseFromString(str, mime as 'text/xml') as unknown as XmlNode & { querySelector: (s: string) => XmlNode | null };
      doc.querySelector = (sel: string) => xmlQuerySelector(doc, sel);
      return doc;
    },
  };
}
import type { TestResult, ResponsePayload } from '../shared/types';
import type { faker as FakerType } from '@faker-js/faker';

// @faker-js/faker v10 is ESM-only — must use dynamic import
let _fakerCache: { faker: typeof FakerType } | null = null;
async function getFaker(): Promise<typeof FakerType> {
  if (!_fakerCache) _fakerCache = await import('@faker-js/faker');
  return _fakerCache.faker;
}

// ─── Public types ─────────────────────────────────────────────────────────────

export interface ScriptContext {
  envVars: Record<string, string>
  collectionVars: Record<string, string>
  globals: Record<string, string>
  localVars: Record<string, string>
  response?: ResponsePayload
  /** Substring patterns matched (case-insensitive) against variable names
   *  when emitting `[set]` console lines. Matched values are redacted so
   *  that secrets extracted via post-script (e.g. access_token) don't leak
   *  into reports or verbose CLI output. */
  piiMaskPatterns?: string[]
}

export interface ScriptOutput {
  testResults: TestResult[]
  consoleOutput: string[]
  updatedEnvVars: Record<string, string>
  updatedCollectionVars: Record<string, string>
  updatedGlobals: Record<string, string>
  updatedLocalVars: Record<string, string>
  error?: string
}

// ─── Chainable Asserter ───────────────────────────────────────────────────────

interface Asserter {
  // Chainers (no-op, return self)
  to: Asserter; be: Asserter; been: Asserter; have: Asserter
  that: Asserter; and: Asserter; is: Asserter; deep: Asserter
  // Negation
  not: Asserter
  // Flag assertions (getter-style, still callable as property)
  ok: Asserter; true: Asserter; false: Asserter; null: Asserter; undefined: Asserter
  // Method assertions
  equal(expected: unknown): Asserter
  eq(expected: unknown): Asserter
  eql(expected: unknown): Asserter
  include(substr: unknown): Asserter
  contain(substr: unknown): Asserter
  property(name: string, expected?: unknown): Asserter
  a(type: string): Asserter
  above(n: number): Asserter; gt(n: number): Asserter
  below(n: number): Asserter; lt(n: number): Asserter
  least(n: number): Asserter; gte(n: number): Asserter
  most(n: number): Asserter;  lte(n: number): Asserter
  oneOf(list: unknown[]): Asserter
  lengthOf(n: number): Asserter
  match(re: RegExp): Asserter
}

function makeAsserter(value: unknown, negated = false): Asserter {
  function doAssert(condition: boolean, msg: string): void {
    const passed = negated ? !condition : condition;
    if (!passed) throw new AssertionError(msg);
  }

  const asserter = {} as Asserter;

  // Chainers
  const chainer = { get: () => asserter };
  for (const key of ['to','be','been','have','that','and','is','deep'] as const) {
    Object.defineProperty(asserter, key, chainer);
  }

  // Negation
  Object.defineProperty(asserter, 'not', { get: () => makeAsserter(value, !negated) });

  // Boolean flag assertions
  Object.defineProperty(asserter, 'ok', { get: () => {
    doAssert(Boolean(value), `Expected ${JSON.stringify(value)} to be truthy`);
    return asserter;
  }});
  Object.defineProperty(asserter, 'true', { get: () => {
    doAssert(value === true, `Expected ${JSON.stringify(value)} to be true`);
    return asserter;
  }});
  Object.defineProperty(asserter, 'false', { get: () => {
    doAssert(value === false, `Expected ${JSON.stringify(value)} to be false`);
    return asserter;
  }});
  Object.defineProperty(asserter, 'null', { get: () => {
    doAssert(value === null, `Expected ${JSON.stringify(value)} to be null`);
    return asserter;
  }});
  Object.defineProperty(asserter, 'undefined', { get: () => {
    doAssert(value === undefined, `Expected value to be undefined`);
    return asserter;
  }});

  // Method assertions
  asserter.equal = (expected) => {
    doAssert(value === expected,
      `Expected ${JSON.stringify(value)} to ${negated ? 'not ' : ''}equal ${JSON.stringify(expected)}`);
    return asserter;
  };
  asserter.eq = asserter.equal;  // Chai alias
  asserter.eql = (expected) => {
    doAssert(JSON.stringify(value) === JSON.stringify(expected),
      `Expected deep equal: ${JSON.stringify(value)} ${negated ? '!=' : '=='} ${JSON.stringify(expected)}`);
    return asserter;
  };
  asserter.include = (substr) => {
    if (typeof value === 'string') {
      doAssert(value.includes(String(substr)),
        `Expected "${value}" to ${negated ? 'not ' : ''}include "${substr}"`);
    } else if (Array.isArray(value)) {
      doAssert(value.includes(substr),
        `Expected array to ${negated ? 'not ' : ''}include ${JSON.stringify(substr)}`);
    }
    return asserter;
  };
  asserter.contain = asserter.include;  // Chai alias
  asserter.property = (name, expected?) => {
    doAssert(value != null && name in Object(value),
      `Expected object to ${negated ? 'not ' : ''}have property "${name}"`);
    if (expected !== undefined) {
      doAssert((value as Record<string, unknown>)[name] === expected,
        `Expected property "${name}" to equal ${JSON.stringify(expected)}`);
    }
    return asserter;
  };
  asserter.a = (type) => {
    const actual = Array.isArray(value) ? 'array' : typeof value;
    doAssert(actual === type,
      `Expected ${JSON.stringify(value)} to ${negated ? 'not ' : ''}be a ${type}`);
    return asserter;
  };
  asserter.above = (n) => {
    doAssert((value as number) > n, `Expected ${value} to ${negated ? 'not ' : ''}be above ${n}`);
    return asserter;
  };
  asserter.below = (n) => {
    doAssert((value as number) < n, `Expected ${value} to ${negated ? 'not ' : ''}be below ${n}`);
    return asserter;
  };
  asserter.least = (n) => {
    doAssert((value as number) >= n, `Expected ${value} to ${negated ? 'not ' : ''}be at least ${n}`);
    return asserter;
  };
  asserter.most = (n) => {
    doAssert((value as number) <= n, `Expected ${value} to ${negated ? 'not ' : ''}be at most ${n}`);
    return asserter;
  };
  asserter.gt = asserter.above; asserter.gte = asserter.least;
  asserter.lt = asserter.below; asserter.lte = asserter.most;

  asserter.oneOf = (list) => {
    doAssert(list.includes(value),
      `Expected ${JSON.stringify(value)} to ${negated ? 'not ' : ''}be one of ${JSON.stringify(list)}`);
    return asserter;
  };
  asserter.lengthOf = (n) => {
    const len = (value as { length: number }).length;
    doAssert(len === n,
      `Expected length ${len} to ${negated ? 'not ' : ''}equal ${n}`);
    return asserter;
  };
  asserter.match = (re) => {
    doAssert(re.test(String(value)),
      `Expected "${value}" to ${negated ? 'not ' : ''}match ${re}`);
    return asserter;
  };

  return asserter;
}

class AssertionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'AssertionError';
  }
}

// ─── Build sp object ──────────────────────────────────────────────────────────

function buildAt(
  ctx: ScriptContext,
  testResults: TestResult[],
  consoleOutput: string[],
) {
  const { envVars, collectionVars, globals, localVars, piiMaskPatterns = [] } = ctx;

  const isSensitiveKey = (key: string) =>
    piiMaskPatterns.some(p => key.toLowerCase().includes(p.toLowerCase()));

  function makeVarScope(store: Record<string, string>, scopeName: string) {
    return {
      get: (key: string) => store[key] ?? null,
      set: (key: string, value: string) => {
        store[key] = String(value);
        const display = isSensitiveKey(key) ? '"[REDACTED]"' : JSON.stringify(String(value));
        consoleOutput.push(`[set] ${scopeName}.${key} = ${display}`);
      },
      clear: (key: string) => {
        delete store[key];
        consoleOutput.push(`[set] ${scopeName}.${key} cleared`);
      },
      has: (key: string) => key in store,
      toObject: () => ({ ...store }),
    };
  }

  const sp: Record<string, unknown> = {
    // Variable scopes
    variables:           makeVarScope(localVars,      'variables'),
    environment:         makeVarScope(envVars,         'environment'),
    collectionVariables: makeVarScope(collectionVars,  'collectionVariables'),
    globals:             makeVarScope(globals,          'globals'),

    // Convenience: get/set across all scopes (local wins)
    variables_get: (key: string) =>
      localVars[key] ?? envVars[key] ?? collectionVars[key] ?? globals[key] ?? null,
    variables_set: (key: string, value: string) => { localVars[key] = String(value); },

    // Test runner
    test: (name: string, fn: () => void) => {
      try {
        fn();
        testResults.push({ name, passed: true });
      } catch (err) {
        testResults.push({
          name,
          passed: false,
          error: err instanceof Error ? err.message : String(err),
        });
      }
    },

    // Expect / assertions
    expect: (value: unknown) => makeAsserter(value, false),

    // JSONPath query: sp.jsonPath(data, '$.store.book[?(@.price < 10)].title')
    jsonPath: (data: unknown, expr: string) =>
      JSONPath({ path: expr, json: data as object }),

    /**
     * Generate a TOTP code from a base32-encoded secret.
     *
     * Usage in scripts:
     *   const code = sp.totp("JBSWY3DPEHPK3PXP");
     *   sp.environment.set("otp", code);
     *
     * Options (all optional):
     *   digits   — code length (default 6)
     *   period   — time step in seconds (default 30)
     *   algorithm — "sha1" | "sha256" | "sha512" (default "sha1")
     */
    totp: (secret: string, options?: { digits?: number; period?: number; algorithm?: string }) => {
      const digits    = options?.digits ?? 6;
      const period    = options?.period ?? 30;
      const algorithm = options?.algorithm ?? 'sha1';

      // Decode base32 secret
      const base32chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
      const cleaned = secret.replace(/[\s=-]/g, '').toUpperCase();
      let bits = '';
      for (const c of cleaned) {
        const val = base32chars.indexOf(c);
        if (val < 0) throw new Error(`Invalid base32 character: ${c}`);
        bits += val.toString(2).padStart(5, '0');
      }
      const keyBytes = Buffer.alloc(Math.floor(bits.length / 8));
      for (let i = 0; i < keyBytes.length; i++) {
        keyBytes[i] = parseInt(bits.slice(i * 8, i * 8 + 8), 2);
      }

      // Compute HMAC over the time counter
      const counter = Math.floor(Date.now() / 1000 / period);
      const counterBuf = Buffer.alloc(8);
      counterBuf.writeUInt32BE(Math.floor(counter / 0x100000000), 0);
      counterBuf.writeUInt32BE(counter >>> 0, 4);

      const hmac = crypto.createHmac(algorithm, keyBytes).update(counterBuf).digest();

      // Dynamic truncation (RFC 4226)
      const offset = hmac[hmac.length - 1] & 0x0f;
      const binCode =
        ((hmac[offset] & 0x7f) << 24) |
        ((hmac[offset + 1] & 0xff) << 16) |
        ((hmac[offset + 2] & 0xff) << 8) |
        (hmac[offset + 3] & 0xff);

      return String(binCode % 10 ** digits).padStart(digits, '0');
    },
  };

  // Attach response helpers if available
  if (ctx.response) {
    const resp = ctx.response;
    let parsedJson: unknown = undefined;

    sp.response = {
      code: resp.status,
      status: `${resp.status} ${resp.statusText}`,
      statusText: resp.statusText,
      responseTime: resp.durationMs,
      responseSize: resp.bodySize,
      headers: {
        get: (name: string) => resp.headers[name.toLowerCase()] ?? null,
        toObject: () => resp.headers,
      },
      json: () => {
        if (parsedJson === undefined) parsedJson = JSON.parse(resp.body);
        return parsedJson;
      },
      text: () => resp.body,
      xmlText: (selector: string) => {
        const doc = new XmlDOMParser().parseFromString(resp.body, 'text/xml') as unknown as XmlNode;
        const node = xmlQuerySelector(doc, selector);
        return node ? String(node.textContent ?? '').trim() : null;
      },
      to: {
        have: {
          status: (code: number) => {
            if (resp.status !== code) throw new AssertionError(`Expected status ${resp.status} to be ${code}`);
          },
        },
      },
    };
  }

  return sp;
}

// ─── Main entry point ─────────────────────────────────────────────────────────

export async function runScript(
  code: string,
  ctx: ScriptContext,
  timeoutMs = 5000,
): Promise<ScriptOutput> {
  const faker = await getFaker();
  const testResults: TestResult[] = [];
  const consoleOutput: string[] = [];

  // Mutable copies that pm modifies in-place
  const envVarsCopy      = { ...ctx.envVars };
  const collectionCopy   = { ...ctx.collectionVars };
  const globalsCopy      = { ...ctx.globals };
  const localVarsCopy    = { ...ctx.localVars };

  const scriptCtx: ScriptContext = {
    envVars:        envVarsCopy,
    collectionVars: collectionCopy,
    globals:        globalsCopy,
    localVars:      localVarsCopy,
    response:       ctx.response,
    piiMaskPatterns: ctx.piiMaskPatterns,
  };

  const sp = buildAt(scriptCtx, testResults, consoleOutput);

  const captureConsole = {
    log:   (...args: unknown[]) => consoleOutput.push(args.map(String).join(' ')),
    warn:  (...args: unknown[]) => consoleOutput.push('[warn] ' + args.map(String).join(' ')),
    error: (...args: unknown[]) => consoleOutput.push('[error] ' + args.map(String).join(' ')),
    info:  (...args: unknown[]) => consoleOutput.push('[info] ' + args.map(String).join(' ')),
  };

  const sandbox = {
    sp,
    DOMParser: makeSandboxDOMParser,
    dayjs,
    faker,
    tv4,
    console: captureConsole,
    JSON,
    Math,
    Date,
    parseInt,
    parseFloat,
    isNaN,
    isFinite,
    encodeURIComponent,
    decodeURIComponent,
    btoa: (s: string) => Buffer.from(s, 'binary').toString('base64'),
    atob: (s: string) => Buffer.from(s, 'base64').toString('binary'),
    setTimeout: undefined,  // not available in sync vm context
    setInterval: undefined,
  };

  try {
    vm.runInNewContext(code, sandbox, { timeout: timeoutMs, filename: 'script.js' });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return {
      testResults,
      consoleOutput,
      updatedEnvVars:        envVarsCopy,
      updatedCollectionVars: collectionCopy,
      updatedGlobals:        globalsCopy,
      updatedLocalVars:      localVarsCopy,
      error: message,
    };
  }

  return {
    testResults,
    consoleOutput,
    updatedEnvVars:        envVarsCopy,
    updatedCollectionVars: collectionCopy,
    updatedGlobals:        globalsCopy,
    updatedLocalVars:      localVarsCopy,
  };
}
